sudo: false

addons:
 apt:
   packages:
     - graphviz

language: scala

scala:
  - 2.11.12
  - 2.12.15
  - 2.13.1

jdk:
  - openjdk11

before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier/

before_script:

before_deploy:

deploy:
  - provider: script
    script: sbt $SBT_ARGS ++$TRAVIS_SCALA_VERSION "set every Seq(sonatypeSessionName := \"Travis Job $TRAVIS_JOB_NAME $TRAVIS_JOB_NUMBER ($TRAVIS_JOB_WEB_URL)\", publishTo := sonatypePublishToBundle.value)" publishSigned sonatypeBundleRelease
    skip_cleanup: true
    on:
      all_branches: true
      condition: $SECRET_GIST

env:
  - SBT_ARGS=
  - SBT_ARGS=--addPluginSbtFile=project/plugins.sbt.scala-js.0.6

sbt_args: $SBT_ARGS
